### ISSUE TITLE
Task Preview bug

### ISSUE THREAD

**Issue by RobKokochak** [RobKokochak/gantt-chart-app#22]
When there's only one task in the Gantt Chart, it cuts off the task preview when you click/hover on it and you can't see the whole task info.
<img width="1265" alt="Screenshot 2022-12-05 at 6 33 34 PM" src="https://user-images.githubusercontent.com/64873559/205767426-e3bba25e-00e5-4350-8814-68a4509c75a4.png">

**Comment by gkosakow** [comment]
fixed in merge #31 by making the gantt chart window larger
