### ISSUE TITLE
Enforce Maximum Project Length

### ISSUE THREAD

**Issue by MatsoA** [RobKokochak/gantt-chart-app#25]
Calculate start and end date of project from tasks so that overall project duration can be calculated

if greg finishes this before me i cry

**Comment by gkosakow** [comment]
https://media.tenor.com/BHyTSZGUEBAAAAAC/cowboy-gun.gif

**Comment by gkosakow** [comment]
![cowboy-gun](https://user-images.githubusercontent.com/99287183/205825172-ec940513-ecb5-4602-a0a1-6f62cb263c7b.gif)

**Comment by MatsoA** [comment]
gave up
